export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SET_TOKEN = 'SET_TOKEN';

export const GET_PATIENTS_REQUEST = 'GET_PATIENTS_REQUEST';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAILURE = 'GET_PATIENTS_FAILURE';

export const BOOK_PATIENT_REQUEST = 'BOOK_PATIENT_REQUEST';
export const BOOK_PATIENT_SUCCESS = 'BOOK_PATIENT_SUCCESS';
export const BOOK_PATIENT_FAILURE = 'BOOK_PATIENT_FAILURE';

export const GET_RULES_REQUEST = 'GET_RULES_REQUEST';
export const GET_RULES_SUCCESS = 'GET_RULES_SUCCESS';
export const GET_RULES_FAILURE = 'GET_RULES_FAILURE';

export const GET_SURVEY_REQUEST = 'GET_SURVEYS_REQUEST';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_FAILURE = 'GET_SURVEY_FAILURE';

export const SAVE_SURVEY_REQUEST = 'SAVE_SURVEYS_REQUEST';
export const SAVE_SURVEY_SUCCESS = 'SAVE_SURVEY_SUCCESS';
export const SAVE_SURVEY_FAILURE = 'SAVE_SURVEY_FAILURE';

export const UNBOOK_PATIENT_REQUEST = 'UNBOOK_PATIENT_REQUEST';
export const UNBOOK_PATIENT_SUCCESS = 'UNBOOK_PATIENT_SUCCESS';
export const UNBOOK_PATIENT_FAILURE = 'UNBOOK_PATIENT_FAILURE';
